### PR TITLE
Remove tslint & configure to use eslint

### PR DESCRIPTION
**Pull request by rajatkantinandi**
## List of changes
- Configure eslint with @typescript-eslint/eslint-plugin & @typescript-eslint/parser
- Add eslint-import-resolver-typescript to resolve imports.
- Copy rules from tslint.json & added matching rules.
- Delete tslint.json file
- Update eslint version
- Add 3 scripts:
  - `lint:eslint:quiet`: linting without warning. 
  - `lint:eslint`: linting with warning. 
  - `lint:eslint:fix`: linting with autofix.
- Modify Pre-commit hook to run: `npm run lint:css && npm run lint:eslint:quiet`

closes: #39 

## React Boilerplate

Thank you for contributing! Please take a moment to review our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
to make the process easy and effective for everyone involved.

**Please open an issue** before embarking on any significant pull request, especially those that
add a new library or change existing tests, otherwise you risk spending a lot of time working
on something that might not end up being merged into the project.

Before opening a pull request, please ensure:

- [x] You have followed our [**contributing guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md)
- [x] Double-check your branch is based on `dev` and targets `dev` 
- [ ] Pull request has tests (we are going for 100% coverage!)
- [ ] Code is well-commented, linted and follows project conventions
- [x] Documentation is updated (if necessary)
- [x] Internal code generators and templates are updated (if necessary)
- [x] Description explains the issue/use-case resolved and auto-closes related issues

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

**IMPORTANT**: By submitting a patch, you agree to allow the project
owners to license your work under the terms of the [MIT License](https://github.com/react-boilerplate/react-boilerplate/blob/master/LICENSE.md).

### CODE REVIEW

**Comment by Can-Sahin** [comment]
Hey. I cannot get travis-ci running for testing pull requests. Can you run `npm run test` and `node ./internals/scripts/generate-templates-for-linting` to see the problems. There are linting problems I can see. 

Few notes:

1- Why `'@typescript-eslint'` is not included in `plugins` ?
2- I think `airbnb-typescript` has to be used for typescript in `extends`

**Comment by rajatkantinandi** [comment]
`npm run test` works fine.
The generated files have some linting errors as below:
`no-unused-vars`: on props in components & containers which is not used.
Can add a disable comment for those lines in the templates.
Error with `arrow-body-style` rule in few places. Not sure about this rule need to check it.
And some prettier styling issues here & there which can be fixed in the template.

1. I'm extending from `@typescript-eslint/recommended` config which automatically adds the plugin, so it was not required to include in plugins. If we extend from `airbnb-typescript` then we will need to add that to plugin.
2. Makes sense to add `airbnb-typescript` in extends as well for ts specific rules. Not sure whether we need both `airbnb` & `airbnb-typescript`, I think just adding `airbnb-typescript` should be fine as this would be a superset of rules of `airbnb`.

What do you think of these changes?

**Comment by rajatkantinandi** [comment]
`arrow-body-style` is set as `as-needed` in the project & the conflict arises when we need to declare the type of the only one param in the arrow function.
So should we disable this rule or set to `always` in which case the templates and the prettier configs need to be modified as well.
What do you think?

**Comment by rajatkantinandi** [comment]
Requested changes are done.
- Now extending from `airbnb-typescript` instead of `airbnb` & added `@typescript-eslint` to plugins.
- Modified templates to match current linting.
- Ran both `npm run test` & `node ./internals/scripts/generate-templates-for-linting` succesfully.

Please check the changes & review.

**Comment by Can-Sahin** [comment]
`node ./internals/scripts/generate-templates-for-linting` doesnt run succeed when  I run locally ?? 

Also when I go to `internals/generator/index.js` I can see the vscode gives an error that that js file isn't included. Same for all js files in generators for instance. Because they are not in `tsconfig` its a [problem](https://github.com/typescript-eslint/typescript-eslint/issues/967#issuecomment-531817014)

Another thing is did you squash your commits ? I can only see a single commit to the pull request but you did several others. I am having hard time tracking changes after I reviewed them. Now everything is a single commit and I cannot track the updates you do after we discuss :(

**Comment by rajatkantinandi** [comment]
Can resolve the tsconfig problem by adding the project options in override only.

Did you run `npm run lint` to see the errors after running `node ./internals/scripts/generate-templates-for-linting`?
In my case there was no errors.

And sorry about the squash. I thought that I was supposed to squash the changes. Won't squash from next time.

**Comment by Can-Sahin** [comment]
> Can resolve the tsconfig problem by adding the project options in override only.

I didnt understand what you mean here. 

There is a problem here. If you look at the original boilerplate `eslint` commands are written without declaring `[file|dir|glob]*` pattern. So whoever calls it passes the file pattern as argument like `npm run lint:eslint -- . `. Now you fixed it to `app/**` which will block all the needed scripts like `npm run lint:eslint "app/${relativePath}/**/**.ts*"`. This shouldnt be the case. If I  run linting with `.` pattern all the `server/` files returns errors. 

Look the the original boilerplate [implementation](https://github.com/react-boilerplate/react-boilerplate/blob/e7dd2887ce568d8bc0ea8db5d0caf0e2c11ff6bd/package.json#L33) that ignores them. You should ignore / filter `internal/scripts`, `generators`, `server/` and all the patterns in gitignore.

This is a process more complicated than simply replacing tslint with eslint. Thats why I postponed it myself ;)

**Comment by rajatkantinandi** [comment]
Yeah I noticed those commands where we can specify files in the command itself rather than running for the whole directory.
I suggest we can have 2 commands one for running by specifying file & one for running in the whole directory.
And for issues with JS files I was looking at typescript-eslint repo & they recommended to create a new tsconfig for linting extending the existing tsconfig & add js files in the include there so the it can parse both JS & TS files.
I will try this out. Should work I think.
Let me know what do you think.

**Comment by rajatkantinandi** [comment]
I tried this out, works fine.
Now can lint both js & ts files based on `tsconfig.eslint.json`.
Also converted the scripts to run per file as you suggested.
Just the `npm run lint` will run for all files as it was earlier.
I hope this works for the use-case you mentioned.
Please check the last commit & let me know.
Thanks.

**Comment by Can-Sahin** [comment]
Ok cool. I havent locally tested yet will do later but my main idea is ignoring all the unnecessary files like `server/` `internal/scripts` and leave the rest. Because we cant force people to put everything in `app/` folder. But now looks like we are only including `app` folder
```  
"include": [
    "app/**/*.ts",
    "app/**/*.tsx",
    "app/**/*.js",
    "app/**/*.jsx",
    "internals/**/*.js",
    "internals/**/*.jsx"
  ]
```

Wouldnt it be better to just exclude things and let eslint include everything rest rather than specify what to include ? This forces people to stick to the folders or manually add their new folders apart from the `app` to eslint config.

My inital idea was just running `eslint` with `"."` pattern (meaning everything), not like `npm run lint:eslint:quiet app/**` which limits things to `app` folder

**Comment by rajatkantinandi** [comment]
Sorry for the delay, was a little busy yesterday.
Requested changes are done.
Now the commands can be run with .
Excluded internal & service folder files & folders in gitignore.
Now we can run in for all javascript & typescript files except from those folders in the exclude.
Please check & review the changes.

**Comment by Can-Sahin** [comment]
Looks good. Gonna test during the weekend hopefully. If no problem then gonna merge. Thanks a lot. I think I will update rules later when I switch to the ducks pattern and redux-tool-kit later. Too many rules. It would be better to stick to recommended ones. But that comes later. There are so many code that will change soon.

**Review by Can-Sahin — APPROVED** [review]

**Pull request merged**
