### PR TITLE
remove types field to fix webpack properties resolution

### PR DESCRIPTION
**Pull request by GrayStrider**
"So, if you have followed convention or used a tooling set such as npm to download @types packages, you don't need to configure typeRoots or types in your configuration as it will work out of the box with the default folder structure."
https://stackoverflow.com/a/42239406/8638301

### CODE REVIEW

**Comment by Can-Sahin** [comment]
will you make more changes ? Is it ready to review ? Looks done to me

**Comment by GrayStrider** [comment]
updated package-lock

**Comment by GrayStrider** [comment]
ready to merge

**Comment by Can-Sahin** [comment]
I merged it but type-checker throws lot of errors now. 

Screen Shot 2019-10-18 at 18 24 36

@GrayStrider  Im gonna revert the pull request now. I deleted nodemodules and package lock and installed again. No change.

**Comment by GrayStrider** [comment]
added fix #41

**Pull request merged**
