### PR TITLE
remove .d from types extension

### PR DESCRIPTION
**Pull request by GrayStrider**
`.d` is meant for ambient types, for example module augmentation; in these cases however, types are explicitly exported and used directly. It's not a huge deal, but it doesn't work in some environments, for example, with `tsconfig-paths-jest`, which expects plain `index.ts` files.

### CODE REVIEW

**Comment by Can-Sahin** [comment]
Can you also fix the scripts renaming `index.d.ts` [here](https://github.com/react-boilerplate/react-boilerplate-typescript/blob/a2b631abb77d7077f50799468e4893882cf0d087/internals/scripts/generate-templates-for-linting.js#L298) and [here](https://github.com/react-boilerplate/react-boilerplate-typescript/blob/a2b631abb77d7077f50799468e4893882cf0d087/internals/generators/container/index.js#L190) and [here](https://github.com/react-boilerplate/react-boilerplate-typescript/blob/a2b631abb77d7077f50799468e4893882cf0d087/internals/generators/container/index.js#L196). Otherwise tests will fail. 

Also can you pull again from `dev`. I just merged eslint feature. So there are easy conflicts.

**Comment by GrayStrider** [comment]
fixed and rebased on eslint, should work

**Comment by GrayStrider** [comment]
Travis reports problem in `app/types/index.ts 41:3`, but there's only 38 lines in that file? idk
I find `react-boilerplate` to be extremely convoluted and overengineered in general tbh

**Comment by Can-Sahin** [comment]
Yeah I know that bug. I will fix soon. Thats why I merged. Now after merging `dev` branch throws more eslint errors on my local and didn't even show up in travis ;(

**Pull request merged**
