### PR TITLE
fix #34

### LINKED ISSUE #34: extract-intl not working
`extract-intl` script isn't working. I commented it out because its blocking language generation script #23 

@GrayStrider you are currently working on this as I see the pull requests. Thanks for it alot. I really dont have time now. If you are up for fixing it, would be super cool

### PR DESCRIPTION
**Pull request by GrayStrider**
uncommented out babel-config typescript plugins,
uncommented extract-intl,
changed ES5 export to module.exports

extract-intl generates translation with no errors:
image

translation messages seemingly unchanged after running generation

### CODE REVIEW

**Comment by GrayStrider** [comment]
using [esm](https://github.com/standard-things/esm) to load `export`, same result, does not require to rewrite imports everywhere `i18n` is used.
no type errors found, tests pass

**Comment by GrayStrider** [comment]
potentially esm could be used in every script that might exhibit similar issues.

**Comment by GrayStrider** [comment]
I might squash these 2 if everything's ok.

**Comment by Can-Sahin** [comment]
Can you explain shortly how `esm` is solving this issue. Im not familiar with it. I think the problem was using `ts` classes in `js` scripts. Im bit behind when it comes to deep ecmascript issues. 

I also disabled babel typescript plugin because firstly it isnt used. `ts-loader` is used. and it ruins something with js classes -> #25 

Any specific reason to bring it back ?

**Comment by GrayStrider** [comment]
Oh, sorry, I just uncommented all code in babel without looking through it, I though you did it just to get rid of an error. Perhaps, make a new PR to remove `babel typescript plugin`.

`Can you explain shortly how esm is solving this issue`
in `i18n.ts` we use `export` syntax (ES6 feature), while in `extract-intl.js ` we import with `require`, which is older syntax. You would have to either change `export` to `module.exports` (what I did in the first commit), but then bunch of things breaks in places when we use `import`, which is supposed to be used with `export`. Or replace `require` with `import` in `extract-intl.js ` I suppose, I haven't tried that. Essentially, I've had similar problems with `export` in the past and found the solution in `esm`, which adds `support ECMAScript modules in Node 6+`. That is of course would be required only for js files, since for typescript compiler takes care of that for us.
I may try to modify `extract-intl.js` if you don't want to add extra dependency, but that's more merge conflicts later.
@Can-Sahin 
for babel configs let's just add everything back and break it down in separate PR's

**Comment by Can-Sahin** [comment]
ok. i udnerstand. This version is fine. Just wanted to understand the reason behind esm module. I ll merge this. But can you commit back the commented-out babel plugin codes. Or you can remove babel plugin typescript entirely. It doesnt support namespaces and in my opinion not ready as ts-loader.

**Comment by GrayStrider** [comment]
> ok. i udnerstand. This version is fine. Just wanted to understand the reason behind esm module. I ll merge this. But can you commit back the commented-out babel plugin codes. Or you can remove babel plugin typescript entirely. It doesnt support namespaces and in my opinion not ready as ts-loader.

done

**Pull request merged**
